# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c26b4a4649b04f841afdafb328a4b3a8fcfaf239a00392a6de3af7e97b9c7fcdde5478568a4004bb34644552b9f797cd96952985f057f6e295c03a97cb7f174c

test:
  secret_key_base: f9369d9d6831980d000855a0902f80f02e1bc093efb21cf3af89b0c542212acac746feeae32e7e78475e24adda64ec33f1f5567b496652449f5eecafd5cb007c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
